Fix BLFReader error for incomplete or truncated stream (#1662)
* bugfix BLFreader

zlib.error: Error -5 while decompressing data: incomplete or truncated stream in Python

* delete elif

copied on to many lines

* Update blf.py

shorten line -> comment in next line
delete unused variable

* fromatting

---------

Co-authored-by: Iding Robin <Robin.Iding@de.bosch.com>