Fix typing annotation for LogReader constructor
A bug was introduced sometime during refactoring of types in the helper
typechecking.py file, when PathLike was renamed to StringPathLike. This
results in mypy complaining that it can't find the PathLike type:

    error: Name 'can.typechecking.PathLike' is not defined

As such, this changes the accepted type for the LogReader constructor
to be a typechecking.StringPathLike.