Add changed byte highlighting to viewer.py (#1159)
* Added optional byte highlighting to viewer

Added optional byte highlighting that can be toggled using the shortcut key 'h'

* Some black formatting changes

* Final black formatting

* Fixed viewer bug

Fix for the following error since the introduction of #1151 / #1142

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/python-can/can/viewer.py", line 582, in <module>
    main()
  File "/home/pi/python-can/can/viewer.py", line 573, in main
    bus = _create_bus(parsed_args, **additional_config, app_name="python-can viewer")
  File "/home/pi/python-can/can/logger.py", line 105, in _create_bus
    if parsed_args.app_name:
AttributeError: 'Namespace' object has no attribute 'app_name'

* Update scripts.rst

update viewer documentations

* Update scripts.rst

* Update scripts.rst

arrange keyboard shortcuts into bulleted list

* Update scripts.rst

* Update can/viewer.py

Co-authored-by: Felix Divo <4403130+felixdivo@users.noreply.github.com>

* Better description.

Add extra length to other lines in the help text so the border lines up.

* Update test_viewer.py

Add test coverage for some of the new byte highlighting functions.

* Use _create_base_argument_parser  in viewer.py

Change standard arguments definition to be defined using logger._create_base_argument_parser instead of manually defining them in this module.

Co-authored-by: Felix Divo <4403130+felixdivo@users.noreply.github.com>