Avoid bogus warning messages upon module import.
Whenever I import this module, a series of warnings messages are printed:

>>> import can
WARNING:root:Kvaser canlib is unavailable.
WARNING:root:Function was not found in library
...
WARNING:root:Function was not found in library
WARNING:root:Kvaser canlib is unavailable.
ERROR:can.serial:You won't be able to use the serial can backend without the
serial module installed!

These come from the Kvaser interface and serial interface modules, which are
imported at the beginning of interface.py. Now, I don't think these messages
are unimportant, but I shouldn't be seeing them if I have no intention of using
either of these interfaces. Rather than remove the messages entirely, we should
only see them when we try to create a bus using the kvaser or serial bustype.

I also had to change the 'from <MODULE> import *' statements to only import the
Bus class name. If you don't make the change, then you get this syntax error:

    SyntaxError: import * only allowed at module level

I'm pretty sure this doesn't change functionality, but I'm not able to test the
Kvaser or PCAN interfaces.